# Generated by Django 5.0.1 on 2024-02-09 17:03

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='users-images', validators=[users.models.validate_file_size]),
        ),
    ]
