# Generated by Django 5.0.1 on 2024-02-15 18:25

import blog.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('summary', models.TextField()),
                ('content', models.TextField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog-images', validators=[blog.models.validate_file_size])),
                ('category', models.CharField(choices=[('Menatl Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('Covid 19', 'Covid 19'), ('Immunization', 'Immunization')], default='Menatl Health', max_length=100)),
                ('drafted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
